services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9101:9100"
    
  loki:
    image: grafana/loki:3.6.7
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/local-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.6.7
    container_name: promtail
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app/logs:/var/log/app
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"

  app:
    build: ./app
    container_name: gerencia-redes-app
    ports:
      - "3003:4000"
    volumes:
      - ./app/logs:/app/logs
    restart: unless-stopped